#
# Automatically generated by tools/build.pl
#

.SUFFIXES: .o .c .h .cpp .s .asm .rc
.PHONY: builds clean

ROOT = .

include $(ROOT)/config.mk

all: builds $(TARGET) $(LIB_TARGET)

builds:
	$(MAKE) -C src/core all
	$(MAKE) -C src/lib/base all
	$(MAKE) -C src/lib/io all
	$(MAKE) -C src/lib/string all
	$(MAKE) -C src/sdrl all

clean:
	$(MAKE) -C src/core clean
	$(MAKE) -C src/lib/base clean
	$(MAKE) -C src/lib/io clean
	$(MAKE) -C src/lib/string clean
	$(MAKE) -C src/sdrl clean

