
SDRL = ../..

LIB_TARGET = $(SDRL)/lib/libsdrl.a
OBJS = machine.o events.o bindings.o expr.o value.o type.o input.o heap.o error.o

CFLAGS = -g -I$(SDRL)/include
ARFLAGS = rc

include $(SDRL)/builder/builder.mk

