

ROOT = ../..

TARGET = sdrl
DIRS = $(ROOT)/src/core $(ROOT)/src/lib/base $(ROOT)/src/lib/io
OBJS = main.o

LIBS = -lbase -lsdrl -lio
CFLAGS = -g -I$(ROOT)/include -L$(ROOT)/lib

include $(ROOT)/rules.mk

