
ROOT = ../../..

LIB_TARGET = $(ROOT)/lib/libbase.a
OBJS =	common/load.o		\
	types/builtin.o		\
	types/expr.o		\
	types/form.o		\
	types/list.o		\
	types/env.o		\
	forms/code.o		\
	funcs/add.o		\
	funcs/and.o		\
	funcs/array.o		\
	funcs/defenv.o		\
	funcs/divide.o		\
	funcs/equals.o		\
	funcs/gthan.o		\
	funcs/gethan.o		\
	funcs/head.o		\
	funcs/if.o		\
	funcs/lethan.o		\
	funcs/list.o		\
	funcs/lookup.o		\
	funcs/lthan.o		\
	funcs/multiply.o	\
	funcs/nequals.o		\
	funcs/not.o		\
	funcs/null.o		\
	funcs/or.o		\
	funcs/print.o		\
	funcs/resolve.o		\
	funcs/set.o		\
	funcs/subtract.o	\
	funcs/tail.o		\
	funcs/unlist.o		\
	parsers/lispy.o		\
	parsers/parser.o	\
	utils/disperr.o		\
	utils/dispexpr.o	\
	utils/parsef.o		\
	utils/parses.o

include $(ROOT)/rules.mk


